"use client";

import { useState, useMemo, useCallback } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Download, X, Check, FileText, Table, FileDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { useToast } from "@/lib/toast-context";
import type { Finding, FindingSeverity, DocumentMetadata } from "@/lib/types";

type ExportFormat = "summary-pdf" | "detailed-pdf" | "csv";

const FORMAT_OPTIONS: {
  value: ExportFormat;
  label: string;
  icon: React.ElementType;
}[] = [
  { value: "summary-pdf", label: "Summary PDF", icon: FileText },
  { value: "detailed-pdf", label: "Detailed PDF", icon: FileDown },
  { value: "csv", label: "CSV Findings Log", icon: Table },
];

const SEVERITY_ORDER: FindingSeverity[] = [
  "critical",
  "major",
  "minor",
  "info",
];
const SEVERITY_LABELS: Record<FindingSeverity, string> = {
  critical: "CRITICAL",
  major: "MAJOR",
  minor: "MINOR",
  info: "INFORMATIONAL",
};
const SEVERITY_HEADER_LINES: Record<FindingSeverity, string> = {
  critical: "─────────────────",
  major: "─────────────",
  minor: "─────────────",
  info: "─────────────────────",
};

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function generateMemoText(
  doc: DocumentMetadata,
  findings: Finding[],
  opts: {
    includeResolved: boolean;
    includeNotes: boolean;
    includeResolutions: boolean;
  },
): string {
  const filtered = opts.includeResolved
    ? findings
    : findings.filter((f) => f.status !== "resolved" && f.status !== "dismissed");

  const counts: Record<FindingSeverity, number> = {
    critical: 0,
    major: 0,
    minor: 0,
    info: 0,
  };
  for (const f of filtered) counts[f.severity]++;

  const lines: string[] = [];
  const hr = "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━";

  lines.push("QA/QC REVIEW MEMO");
  lines.push(hr);
  lines.push("");
  lines.push(`Document:    ${doc.documentName}`);
  lines.push(`Prepared by: ${doc.author}`);
  lines.push(`Review Date: ${formatDate(new Date())}`);
  lines.push(`Reviewer:    [AI-Assisted Review — EnviroQA v0.1]`);
  lines.push("");
  lines.push(`QA Readiness Score: ${doc.overallScore}/100`);
  lines.push(`(Measures document completeness, consistency, and citation accuracy)`);
  lines.push("");
  lines.push("");
  lines.push("SUMMARY OF FINDINGS");
  lines.push("━━━━━━━━━━━━━━━━━━");
  lines.push("");
  lines.push(
    `Critical: ${counts.critical} | Major: ${counts.major} | Minor: ${counts.minor} | Informational: ${counts.info}`,
  );
  lines.push("");

  for (const sev of SEVERITY_ORDER) {
    const group = filtered.filter((f) => f.severity === sev);
    if (group.length === 0) continue;

    lines.push("");
    lines.push(`${SEVERITY_LABELS[sev]} FINDINGS`);
    lines.push(SEVERITY_HEADER_LINES[sev]);

    for (const f of group) {
      lines.push("");
      lines.push(`[${f.id}] ${f.title}`);
      if (f.location) lines.push(`Location: ${f.location}`);
      if (f.regulation) lines.push(`Regulation: ${f.regulation}`);
      lines.push(`Status: ${f.status.charAt(0).toUpperCase() + f.status.slice(1)}`);
      lines.push(`Description: ${f.description}`);
      if (opts.includeResolutions && f.suggestedResolution) {
        lines.push(`Recommended Action: ${f.suggestedResolution}`);
      }
      if (opts.includeNotes && f.reviewerNote) {
        lines.push(`Reviewer Note: ${f.reviewerNote}`);
      }
    }
  }

  lines.push("");
  lines.push("");
  lines.push(hr);
  lines.push("END OF REPORT");
  lines.push(
    `Generated by EnviroQA v0.1 on ${formatDate(new Date())}`,
  );

  return lines.join("\n");
}

function MemoPreview({
  doc,
  findings,
  includeResolved,
  includeNotes,
  includeResolutions,
}: {
  doc: DocumentMetadata;
  findings: Finding[];
  includeResolved: boolean;
  includeNotes: boolean;
  includeResolutions: boolean;
}) {
  const filtered = includeResolved
    ? findings
    : findings.filter((f) => f.status !== "resolved" && f.status !== "dismissed");

  const counts: Record<FindingSeverity, number> = {
    critical: 0,
    major: 0,
    minor: 0,
    info: 0,
  };
  for (const f of filtered) counts[f.severity]++;

  return (
    <div className="font-mono text-[11px] leading-relaxed text-neutral-800 space-y-0">
      <p className="text-sm font-bold tracking-wide">QA/QC REVIEW MEMO</p>
      <p className="text-neutral-400 text-[10px]">
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      </p>
      <div className="h-3" />

      <table className="text-[11px]">
        <tbody>
          <tr>
            <td className="pr-3 text-neutral-500 align-top whitespace-nowrap">
              Document:
            </td>
            <td>{doc.documentName}</td>
          </tr>
          <tr>
            <td className="pr-3 text-neutral-500 align-top whitespace-nowrap">
              Prepared by:
            </td>
            <td>{doc.author}</td>
          </tr>
          <tr>
            <td className="pr-3 text-neutral-500 align-top whitespace-nowrap">
              Review Date:
            </td>
            <td>{formatDate(new Date())}</td>
          </tr>
          <tr>
            <td className="pr-3 text-neutral-500 align-top whitespace-nowrap">
              Reviewer:
            </td>
            <td>[AI-Assisted Review — EnviroQA v0.1]</td>
          </tr>
        </tbody>
      </table>

      <div className="h-2" />
      <p>
        <span className="text-neutral-500">QA Readiness Score:</span>{" "}
        <span className="font-bold text-neutral-900">
          {doc.overallScore}/100
        </span>
      </p>
      <p className="text-[9px] text-neutral-400">
        Measures document completeness, consistency, and citation accuracy
      </p>

      <div className="h-5" />
      <p className="font-bold tracking-wide">SUMMARY OF FINDINGS</p>
      <p className="text-neutral-400 text-[10px]">
        ━━━━━━━━━━━━━━━━━━
      </p>
      <div className="h-1" />
      <p>
        <span className="text-red-700 font-semibold">
          Critical: {counts.critical}
        </span>
        {" | "}
        <span className="text-amber-700 font-semibold">
          Major: {counts.major}
        </span>
        {" | "}
        <span className="text-yellow-700 font-semibold">
          Minor: {counts.minor}
        </span>
        {" | "}
        <span className="text-blue-700 font-semibold">
          Informational: {counts.info}
        </span>
      </p>

      {SEVERITY_ORDER.map((sev) => {
        const group = filtered.filter((f) => f.severity === sev);
        if (group.length === 0) return null;

        const colorClass =
          sev === "critical"
            ? "text-red-800"
            : sev === "major"
              ? "text-amber-800"
              : sev === "minor"
                ? "text-yellow-800"
                : "text-blue-800";

        return (
          <div key={sev} className="mt-5">
            <p className={cn("font-bold tracking-wide", colorClass)}>
              {SEVERITY_LABELS[sev]} FINDINGS
            </p>
            <p className="text-neutral-300 text-[10px]">
              {SEVERITY_HEADER_LINES[sev]}
            </p>

            {group.map((f) => (
              <div key={f.id} className="mt-3 pl-1">
                <p className="font-semibold">
                  <span className="text-neutral-500">[{f.id}]</span>{" "}
                  {f.title}
                </p>
                {f.location && (
                  <p className="text-neutral-600">
                    <span className="text-neutral-400">Location:</span>{" "}
                    {f.location}
                  </p>
                )}
                {f.regulation && (
                  <p className="text-neutral-600">
                    <span className="text-neutral-400">Regulation:</span>{" "}
                    {f.regulation}
                  </p>
                )}
                <p className="text-neutral-600">
                  <span className="text-neutral-400">Description:</span>{" "}
                  {f.description}
                </p>
                {includeResolutions && f.suggestedResolution && (
                  <p className="text-neutral-600">
                    <span className="text-neutral-400">
                      Recommended Action:
                    </span>{" "}
                    {f.suggestedResolution}
                  </p>
                )}
                {includeNotes && f.reviewerNote && (
                  <p className="text-neutral-600 italic">
                    <span className="text-neutral-400 not-italic">
                      Reviewer Note:
                    </span>{" "}
                    {f.reviewerNote}
                  </p>
                )}
              </div>
            ))}
          </div>
        );
      })}

      <div className="h-6" />
      <p className="text-neutral-400 text-[10px]">
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      </p>
      <p className="text-neutral-400">END OF REPORT</p>
      <p className="text-neutral-400 text-[10px]">
        Generated by EnviroQA v0.1 on {formatDate(new Date())}
      </p>
    </div>
  );
}

function Checkbox({
  id,
  checked,
  onChange,
  label,
}: {
  id: string;
  checked: boolean;
  onChange: (v: boolean) => void;
  label: string;
}) {
  return (
    <label
      htmlFor={id}
      className="flex items-center gap-2.5 cursor-pointer group"
    >
      <button
        id={id}
        role="checkbox"
        aria-checked={checked}
        onClick={() => onChange(!checked)}
        className={cn(
          "w-4 h-4 rounded border flex items-center justify-center transition-all shrink-0",
          checked
            ? "bg-accent border-accent"
            : "border-border bg-surface-elevated group-hover:border-text-muted",
        )}
      >
        {checked && <Check size={12} className="text-white" strokeWidth={3} />}
      </button>
      <span className="text-sm text-text-secondary">{label}</span>
    </label>
  );
}

export default function ExportReport({
  findings,
  document: doc,
}: {
  findings: Finding[];
  document: DocumentMetadata;
}) {
  const [open, setOpen] = useState(false);
  const [format, setFormat] = useState<ExportFormat>("summary-pdf");
  const [includeResolved, setIncludeResolved] = useState(false);
  const [includeNotes, setIncludeNotes] = useState(true);
  const [includeResolutions, setIncludeResolutions] = useState(true);
  const { addToast } = useToast();

  const handleExport = useCallback(() => {
    const text = generateMemoText(doc, findings, {
      includeResolved,
      includeNotes,
      includeResolutions,
    });

    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement("a");
    a.href = url;
    a.download = `QA-QC-Review-Memo-${new Date().toISOString().slice(0, 10)}.txt`;
    window.document.body.appendChild(a);
    a.click();
    window.document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setOpen(false);
    addToast("Report exported successfully");
  }, [doc, findings, includeResolved, includeNotes, includeResolutions, addToast]);

  const previewFindings = useMemo(() => {
    return includeResolved
      ? findings
      : findings.filter(
          (f) => f.status !== "resolved" && f.status !== "dismissed",
        );
  }, [findings, includeResolved]);

  return (
    <>
      <Dialog.Root open={open} onOpenChange={setOpen}>
        <Dialog.Trigger asChild>
          <button className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-text-secondary border border-border rounded hover:bg-surface-elevated transition-colors cursor-pointer">
            <Download size={15} />
            Export Report
          </button>
        </Dialog.Trigger>

        <Dialog.Portal>
          <Dialog.Overlay className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=closed]:animate-out data-[state=closed]:fade-out-0" />
          <Dialog.Content className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 z-50 w-[680px] max-h-[90vh] bg-surface border border-border rounded-lg shadow-2xl flex flex-col data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95">
            {/* Header */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-border shrink-0">
              <Dialog.Title className="text-base font-semibold text-text-primary">
                Export QA/QC Review Memo
              </Dialog.Title>
              <Dialog.Close className="p-1 rounded hover:bg-surface-elevated text-text-muted hover:text-text-secondary transition-colors cursor-pointer">
                <X size={18} />
              </Dialog.Close>
            </div>

            {/* Body */}
            <div className="flex-1 overflow-y-auto px-5 py-4 space-y-5">
              {/* Format selector */}
              <div>
                <label className="text-xs font-semibold text-text-muted uppercase tracking-wider block mb-2">
                  Export Format
                </label>
                <div className="flex gap-2">
                  {FORMAT_OPTIONS.map((opt) => {
                    const Icon = opt.icon;
                    const active = format === opt.value;
                    return (
                      <button
                        key={opt.value}
                        onClick={() => setFormat(opt.value)}
                        className={cn(
                          "flex items-center gap-2 px-3 py-2 rounded border text-sm font-medium transition-all cursor-pointer",
                          active
                            ? "border-accent bg-accent/10 text-accent"
                            : "border-border bg-surface-elevated text-text-secondary hover:border-text-muted",
                        )}
                      >
                        <Icon size={15} />
                        {opt.label}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Options */}
              <div>
                <label className="text-xs font-semibold text-text-muted uppercase tracking-wider block mb-2.5">
                  Options
                </label>
                <div className="space-y-2.5">
                  <Checkbox
                    id="include-resolved"
                    checked={includeResolved}
                    onChange={setIncludeResolved}
                    label="Include resolved findings"
                  />
                  <Checkbox
                    id="include-notes"
                    checked={includeNotes}
                    onChange={setIncludeNotes}
                    label="Include reviewer notes"
                  />
                  <Checkbox
                    id="include-resolutions"
                    checked={includeResolutions}
                    onChange={setIncludeResolutions}
                    label="Include suggested resolutions"
                  />
                </div>
              </div>

              {/* Preview */}
              <div>
                <label className="text-xs font-semibold text-text-muted uppercase tracking-wider block mb-2">
                  Preview
                </label>
                <div className="bg-white rounded-md border border-neutral-200 shadow-inner max-h-[340px] overflow-y-auto px-6 py-5">
                  <MemoPreview
                    doc={doc}
                    findings={previewFindings}
                    includeResolved={includeResolved}
                    includeNotes={includeNotes}
                    includeResolutions={includeResolutions}
                  />
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="flex items-center justify-between px-5 py-3 border-t border-border shrink-0">
              <p className="text-xs text-text-muted">
                {previewFindings.length} finding
                {previewFindings.length !== 1 && "s"} will be included
              </p>
              <div className="flex items-center gap-2">
                <Dialog.Close className="px-3 py-1.5 text-sm font-medium text-text-secondary border border-border rounded hover:bg-surface-elevated transition-colors cursor-pointer">
                  Cancel
                </Dialog.Close>
                <button
                  onClick={handleExport}
                  className="flex items-center gap-1.5 px-4 py-1.5 text-sm font-semibold text-white bg-accent rounded hover:bg-accent/90 transition-colors cursor-pointer"
                >
                  <Download size={15} />
                  Export
                </button>
              </div>
            </div>
          </Dialog.Content>
        </Dialog.Portal>
      </Dialog.Root>

    </>
  );
}
